version: 1.0.{build}

environment:
  matrix:
  - program: pw-auto-login
    name: win32
    platform: amd64_x86
    qt: msvc2017
  - program: pw-auto-login
    name: win64
    platform: amd64
    qt: msvc2017_64

init:
  # Add Qt binaries (qmake, jom, windeployqt) to PATH 
  - set PATH=C:\Qt\5.14.2\%qt%\bin;%PATH%
  # Properly set VS environment variables according to the platform
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

before_build:
  - md build

build_script:
  # Generate Makefile from .pro file, and put it into build dir
  - qmake %program%.pro -o build/Makefile
  - cd build
  - nmake

after_build:
  - md deploy
  - cd deploy
  - move ..\release\%program%.exe .
  - windeployqt --no-compiler-runtime %program%.exe
  - move %program%.exe "Pw AutoLogin.exe"
  - 7z a PwAutoLogin_%name%.zip *
  - move PwAutoLogin_%name%.zip %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: PwAutoLogin_%name%.zip
    name: PwAutoLogin_%name%.zip

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Pw AutoLogin utility'
  provider: GitHub
  auth_token:
    secure: yj2HwlSUjH5HqEQ2mQFQuBxJCZyIyp2T0cecESgkyXaLf0sVC0KjEUr0dgJyZupQ
  artifact: PwAutoLogin_%name%.zip
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
